apiVersion: v1
kind: Pod
metadata:
  name: nginx-read-only-container2
spec:
  containers:
    - image: nginx
      name: nginx-read-only-container2
      securityContext:
        readOnlyRootFilesystem: true
      volumeMounts:
        - mountPath: /var/cache/nginx/
          name: cache-volume
        - mountPath: /var/run
          name: runtime-volume
  volumes:
    - name: cache-volume
      emptyDir: {}
    - name: runtime-volume
      emptyDir: {}

