apiVersion: v1
kind: Pod
metadata:
  name: nginx-seccomp-unconfined
spec:
  containers:
    - image: nginx
      name: nginx
      resources: {}
      securityContext:
        seccompProfile:
          type: Unconfined