apiVersion: v1
kind: Pod
metadata:
  name: liveness-http-pod
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        # using a named port
        - name: http
          containerPort: 80
      livenessProbe:
        httpGet:
          path: /
          port: http
        initialDelaySeconds: 5
        periodSeconds: 5
