apiVersion: v1
kind: Pod
metadata:
  name: sidecar-pod
spec:
  containers:
    - name: busybox1
      image: busybox
      command:
        - sh
        - -c
        - while true; do echo logs data >> /output/output.log; sleep 5; done
      volumeMounts:
        - mountPath: /output
          name: shared-volume
    - name: busybox2
      image: busybox
      command:
        - sh
        - -c
        - tail -f /input/output.log
      volumeMounts:
        - mountPath: /input
          name: shared-volume
  volumes:
    - name: shared-volume
      emptyDir: {}

