apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  # creates a non expiring token just like how it was before v1.22/v1.24
  name: my-sa-token
  annotations:
    kubernetes.io/service-account.name: my-sa
