apiVersion: v1
kind: Pod
metadata:
  name: nginx-cpu-limit-range
  labels:
    app: nginx
    version: v1
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80
      resources:
        requests:
          # Error from server (Forbidden): error when creating "nginx-cpu-limit-range.yaml": pods "nginx-cpu-limit-range" is forbidden:
          # minimum cpu usage per Container is 100m, but request is 50m
          cpu: 50m


