apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-rollout
  labels:
    app: nginx
  annotations:
    kubernetes.io/change-cause: "Updated image to my-image:tag"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.29.1