apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  # create 3 completed pod one of after other you can parallelize it with `parallelism: 3`
  completions: 3
  template:
    spec:
      containers:
        - name: pi
          image: perl:5.34.0
          command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
  backoffLimit: 4