apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - nginx-deployment.yaml
  - nginx-service.yaml

labels:
  - pairs:
      org: Mimacom
    includeTemplates: true # <-- false by default

commonAnnotations:
  branch: master

configMapGenerator:
  - name: my-application-properties
    files:
      - application.properties

secretGenerator:
  - name: my-secrets
    literals:
      - password=verysecret

