---
apiVersion: v1
kind: Pod
metadata:
  name: resource-pod
spec:
  containers:
    - name: busybox
      image: busybox
      command:
        - "sh"
        - "-c"
        - "while true; do sleep 3600; done"
      resources:
        requests:
          memory: "128Mi"
          cpu: "256m"
        limits:
          memory: "256Mi"
          cpu: "500m"