apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
namespace: dev
namePrefix: dev-

# https://datatracker.ietf.org/doc/html/rfc6902
# externalise file
patches:
  - path: deployment-patch.yaml
    target:
      kind: Service
      name: nginx-service
  - path: service-patch.yaml
    target:
      kind: Deployment
      name: nginx-deployment
