apiVersion: v1
kind: Pod
metadata:
  name: pv-pod
spec:
  containers:
    - name: busybox
      image: busybox
      command: [ 'sh', '-c', 'while true; do echo Success!! >> /output/output.txt; sleep 5; done' ]
      volumeMounts:
        - name: pv-volume
          mountPath: /output
  volumes:
    - name: pv-volume
      persistentVolumeClaim:
        claimName: my-pvc
